version: '3.7'
services:
  lgen:
    build: ./lgen
    image: caeltintreach/lgen:latest
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - target: 5001
        published: 5001
        protocol: tcp
  ngen:
    build: ./ngen
    image: caeltintreach/ngen:latest
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - target: 5002
        published: 5002
        protocol: tcp
  pgen:
    build: ./pgen
    image: caeltintreach/pgen:latest
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - target: 5003
        published: 5003
        protocol: tcp
  ui:
    build: ./ui
    image: caeltintreach/ui:latest
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    environment: 
      DATABASE_URI: ${DATABASE_URI}
  database:
    image: mysql:5.7
    ports:
      - target: 3306
        published: 3306
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: prizedb
    volumes:
      - type: volume
        source: prizedb
        target: /var/lib/mysql

volumes:
  prizedb:

#export DATABASE_URI=mysql+pymysql://root:root@database:3306/prizedb
#export MYSQL_ROOT_PASSWORD=root