version: '3.7'
services:
  lgen:
    build: ./lgen
    ports:
      - target: 5001
        published: 5001
        protocol: tcp
  ngen:
    build: ./ngen
    ports:
      - target: 5002
        published: 5002
        protocol: tcp
  pgen:
    image: 127.0.0.1:4999/pgen
    build: ./pgen
    ports:
      - target: 5003
        published: 5003
        protocol: tcp
  ui:
    image: 127.0.0.1:4999/ui
    build: ./ui
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    deploy:
      replicas: 2
    environment: 
      DATABASE_URI: ${DATABASE_URI}
  database:
    image: mysql:5.7
    ports:
      - target: 3306
        published: 3306
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: prizedb
    volumes:
      - type: volume
        source: database-volume
        target: /var/lib/mysql

volumes:
  prizedb:

#export DATABASE_URI=mysql_pymysql://root:root@database:3306/prizedb
#export MYSQL_ROOT_PASSWORD=root